titre: Autodépendance
a_propos: Nous sommes un collectif basé à Montréal qui désire participer au débat public autour d'une politique de mobilité durable.
sections:
  - id: home
    href: /index.html
    titre: Accueil
  - id: apropos
    href: /apropos.html
    titre: À propos
  - id: blogue
    href: /blogue.html
    titre: Blogue
  - id: contact
    href: /contact.html
    titre: Contact
  - id: twitter
    href: https://twitter.com/autodependance
    titre: Twitter
  - id: facebook
    href: https://www.facebook.com/groups/autodependance
    titre: Facebook

# Notre site utilise https://formspree.io pour les formulaires.
formspree_token: mqkereej
